/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RegistrazioneRouteImport } from './routes/registrazione'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminContabilitaRouteImport } from './routes/_authenticated/admin/contabilita'
import { Route as AuthenticatedAdminOrdiniRouteImport } from './routes/_authenticated/admin/ordini'
import { Route as AuthenticatedAdminPromozioniRouteImport } from './routes/_authenticated/admin/promozioni'
import { Route as AuthenticatedAdminUtentiRouteImport } from './routes/_authenticated/admin/utenti'
import { Route as AuthenticatedClienteIndexRouteImport } from './routes/_authenticated/cliente/index'
import { Route as AuthenticatedClienteOrdiniRouteImport } from './routes/_authenticated/cliente/ordini'
import { Route as AuthenticatedClienteContabilitaRouteImport } from './routes/_authenticated/cliente/contabilita'
import { Route as AuthenticatedOperatoreIndexRouteImport } from './routes/_authenticated/operatore/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrazioneRoute = RegistrazioneRouteImport.update({
  id: '/registrazione',
  path: '/registrazione',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminContabilitaRoute =
  AuthenticatedAdminContabilitaRouteImport.update({
    id: '/admin/contabilita',
    path: '/admin/contabilita',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrdiniRoute =
  AuthenticatedAdminOrdiniRouteImport.update({
    id: '/admin/ordini',
    path: '/admin/ordini',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPromozioniRoute =
  AuthenticatedAdminPromozioniRouteImport.update({
    id: '/admin/promozioni',
    path: '/admin/promozioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUtentiRoute =
  AuthenticatedAdminUtentiRouteImport.update({
    id: '/admin/utenti',
    path: '/admin/utenti',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteIndexRoute =
  AuthenticatedClienteIndexRouteImport.update({
    id: '/cliente/',
    path: '/cliente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteOrdiniRoute =
  AuthenticatedClienteOrdiniRouteImport.update({
    id: '/cliente/ordini',
    path: '/cliente/ordini',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteContabilitaRoute =
  AuthenticatedClienteContabilitaRouteImport.update({
    id: '/cliente/contabilita',
    path: '/cliente/contabilita',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatoreIndexRoute =
  AuthenticatedOperatoreIndexRouteImport.update({
    id: '/operatore/',
    path: '/operatore/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/registrazione': typeof RegistrazioneRoute
  '/admin/contabilita': typeof AuthenticatedAdminContabilitaRoute
  '/admin/ordini': typeof AuthenticatedAdminOrdiniRoute
  '/admin/promozioni': typeof AuthenticatedAdminPromozioniRoute
  '/admin/utenti': typeof AuthenticatedAdminUtentiRoute
  '/cliente/contabilita': typeof AuthenticatedClienteContabilitaRoute
  '/cliente/ordini': typeof AuthenticatedClienteOrdiniRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cliente/': typeof AuthenticatedClienteIndexRoute
  '/operatore/': typeof AuthenticatedOperatoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/registrazione': typeof RegistrazioneRoute
  '/admin/contabilita': typeof AuthenticatedAdminContabilitaRoute
  '/admin/ordini': typeof AuthenticatedAdminOrdiniRoute
  '/admin/promozioni': typeof AuthenticatedAdminPromozioniRoute
  '/admin/utenti': typeof AuthenticatedAdminUtentiRoute
  '/cliente/contabilita': typeof AuthenticatedClienteContabilitaRoute
  '/cliente/ordini': typeof AuthenticatedClienteOrdiniRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/cliente': typeof AuthenticatedClienteIndexRoute
  '/operatore': typeof AuthenticatedOperatoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/registrazione': typeof RegistrazioneRoute
  '/_authenticated/admin/contabilita': typeof AuthenticatedAdminContabilitaRoute
  '/_authenticated/admin/ordini': typeof AuthenticatedAdminOrdiniRoute
  '/_authenticated/admin/promozioni': typeof AuthenticatedAdminPromozioniRoute
  '/_authenticated/admin/utenti': typeof AuthenticatedAdminUtentiRoute
  '/_authenticated/cliente/contabilita': typeof AuthenticatedClienteContabilitaRoute
  '/_authenticated/cliente/ordini': typeof AuthenticatedClienteOrdiniRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cliente/': typeof AuthenticatedClienteIndexRoute
  '/_authenticated/operatore/': typeof AuthenticatedOperatoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/registrazione'
    | '/admin/contabilita'
    | '/admin/ordini'
    | '/admin/promozioni'
    | '/admin/utenti'
    | '/cliente/contabilita'
    | '/cliente/ordini'
    | '/admin/'
    | '/cliente/'
    | '/operatore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/registrazione'
    | '/admin/contabilita'
    | '/admin/ordini'
    | '/admin/promozioni'
    | '/admin/utenti'
    | '/cliente/contabilita'
    | '/cliente/ordini'
    | '/admin'
    | '/cliente'
    | '/operatore'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/registrazione'
    | '/_authenticated/admin/contabilita'
    | '/_authenticated/admin/ordini'
    | '/_authenticated/admin/promozioni'
    | '/_authenticated/admin/utenti'
    | '/_authenticated/cliente/contabilita'
    | '/_authenticated/cliente/ordini'
    | '/_authenticated/admin/'
    | '/_authenticated/cliente/'
    | '/_authenticated/operatore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegistrazioneRoute: typeof RegistrazioneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrazione': {
      id: '/registrazione'
      path: '/registrazione'
      fullPath: '/registrazione'
      preLoaderRoute: typeof RegistrazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contabilita': {
      id: '/_authenticated/admin/contabilita'
      path: '/admin/contabilita'
      fullPath: '/admin/contabilita'
      preLoaderRoute: typeof AuthenticatedAdminContabilitaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ordini': {
      id: '/_authenticated/admin/ordini'
      path: '/admin/ordini'
      fullPath: '/admin/ordini'
      preLoaderRoute: typeof AuthenticatedAdminOrdiniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/promozioni': {
      id: '/_authenticated/admin/promozioni'
      path: '/admin/promozioni'
      fullPath: '/admin/promozioni'
      preLoaderRoute: typeof AuthenticatedAdminPromozioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/utenti': {
      id: '/_authenticated/admin/utenti'
      path: '/admin/utenti'
      fullPath: '/admin/utenti'
      preLoaderRoute: typeof AuthenticatedAdminUtentiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/': {
      id: '/_authenticated/cliente/'
      path: '/cliente'
      fullPath: '/cliente/'
      preLoaderRoute: typeof AuthenticatedClienteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/contabilita': {
      id: '/_authenticated/cliente/contabilita'
      path: '/cliente/contabilita'
      fullPath: '/cliente/contabilita'
      preLoaderRoute: typeof AuthenticatedClienteContabilitaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/ordini': {
      id: '/_authenticated/cliente/ordini'
      path: '/cliente/ordini'
      fullPath: '/cliente/ordini'
      preLoaderRoute: typeof AuthenticatedClienteOrdiniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operatore/': {
      id: '/_authenticated/operatore/'
      path: '/operatore'
      fullPath: '/operatore/'
      preLoaderRoute: typeof AuthenticatedOperatoreIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminContabilitaRoute: typeof AuthenticatedAdminContabilitaRoute
  AuthenticatedAdminOrdiniRoute: typeof AuthenticatedAdminOrdiniRoute
  AuthenticatedAdminPromozioniRoute: typeof AuthenticatedAdminPromozioniRoute
  AuthenticatedAdminUtentiRoute: typeof AuthenticatedAdminUtentiRoute
  AuthenticatedClienteContabilitaRoute: typeof AuthenticatedClienteContabilitaRoute
  AuthenticatedClienteOrdiniRoute: typeof AuthenticatedClienteOrdiniRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedClienteIndexRoute: typeof AuthenticatedClienteIndexRoute
  AuthenticatedOperatoreIndexRoute: typeof AuthenticatedOperatoreIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminContabilitaRoute: AuthenticatedAdminContabilitaRoute,
  AuthenticatedAdminOrdiniRoute: AuthenticatedAdminOrdiniRoute,
  AuthenticatedAdminPromozioniRoute: AuthenticatedAdminPromozioniRoute,
  AuthenticatedAdminUtentiRoute: AuthenticatedAdminUtentiRoute,
  AuthenticatedClienteContabilitaRoute: AuthenticatedClienteContabilitaRoute,
  AuthenticatedClienteOrdiniRoute: AuthenticatedClienteOrdiniRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedClienteIndexRoute: AuthenticatedClienteIndexRoute,
  AuthenticatedOperatoreIndexRoute: AuthenticatedOperatoreIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RegistrazioneRoute: RegistrazioneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
